<?php
/*
Plugin Name: WordPress Staging Site Redirect
Plugin URI: https://leodandesign.co.uk
Description: Stops Search Engines Indexing Staging Sites & Redirects To Main Site
Author: Ben Matthews / Leodan:Design
Author URI: https://benjaminmatthews.me.uk
Version: 1.0
License: GPLv2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
*/

function wp_staging_add_meta_noindex() {
	$meta_tag = '<meta name="robots" content="noindex">';
	return $meta_tag;
}
add_action('wp_head', 'wp_staging_add_meta_noindex');

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class StagingSiteRedirects {
	private $staging_site_redirects_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'staging_site_redirects_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'staging_site_redirects_page_init' ) );
	}

	public function staging_site_redirects_add_plugin_page() {
		add_menu_page(
			'Staging Site Redirects', // page_title
			'Staging Site Redirects', // menu_title
			'manage_options', // capability
			'staging-site-redirects', // menu_slug
			array( $this, 'staging_site_redirects_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function staging_site_redirects_create_admin_page() {
		$this->staging_site_redirects_options = get_option( 'staging_site_redirects_option_name' ); ?>

		<div class="wrap">
			<h2>Staging Site Redirects</h2>
			<p>Setttings For WordPress Staging Site Redirects Plugins</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'staging_site_redirects_option_group' );
					do_settings_sections( 'staging-site-redirects-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function staging_site_redirects_page_init() {
		register_setting(
			'staging_site_redirects_option_group', // option_group
			'staging_site_redirects_option_name', // option_name
			array( $this, 'staging_site_redirects_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'staging_site_redirects_setting_section', // id
			'Settings', // title
			array( $this, 'staging_site_redirects_section_info' ), // callback
			'staging-site-redirects-admin' // page
		);

		add_settings_field(
			'main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0', // id
			'Main Site Url (Will redirect all non-logged in users to this site)', // title
			array( $this, 'main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0_callback' ), // callback
			'staging-site-redirects-admin', // page
			'staging_site_redirects_setting_section' // section
		);
	}

	public function staging_site_redirects_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0'] ) ) {
			$sanitary_values['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0'] = sanitize_text_field( $input['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0'] );
		}

		return $sanitary_values;
	}

	public function staging_site_redirects_section_info() {
		
	}

	public function main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="staging_site_redirects_option_name[main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0]" id="main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0" value="%s">',
			isset( $this->staging_site_redirects_options['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0'] ) ? esc_attr( $this->staging_site_redirects_options['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0']) : ''
		);
	}

}
if ( is_admin() )
	$staging_site_redirects = new StagingSiteRedirects();

/* 
 * Retrieve this value with:
 * $staging_site_redirects_options = get_option( 'staging_site_redirects_option_name' ); // Array of All Options
 * $main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0 = $staging_site_redirects_options['main_site_url_will_redirect_all_non_logged_in_users_to_this_site_0']; // Main Site Url (Will redirect all non-logged in users to this site)
 */
